### ISSUE TITLE
how to run the docker command in dockerfile?

### ISSUE THREAD

**Issue by cherry4477** [cf-platform-eng/rds-broker#1]
in the dockerfile there is a docker build command,but in container there isn't docker

**Comment by frodenas** [comment]
If you want to build the docker image, you'll need to run the [build-docker-image](https://github.com/cf-platform-eng/rds-broker/blob/master/bin/build-docker-image) script. This script will use the external docker daemon by passing the appropriate environment variables.

Please run this script and let me known if you still face any problem.
