### ISSUE TITLE
Is the broker being maintained and used?

### ISSUE THREAD

**Issue by bleach** [cf-platform-eng/rds-broker#2]
Hi,

This isn't really an issue, but I couldn't see anywhere to discuss usage. Feel free to redirect me to a more appropriate channel for discussion if there is one.

The broker hasn't seen many changes recently and the README says it is not ready for production use. Is anyone using it in production, and if so, what's the verdict on suitability for production now? What would need to be done to make it ready for production?

Thanks,
Graham

**Comment by frodenas** [comment]
This broker was part of an experiment to demonstrate the [updates to the Service Broker API](https://blog.pivotal.io/pivotal-cloud-foundry/products/a-look-at-cloud-foundrys-service-broker-updates), and has never been my intention to create a production ready product. I don't know if anyone is using it in production.

Said that, Pivotal is evaluating creating some service brokers for certain AWS services. Let me know if you're interested and I can put you in contact with the corresponding PM.

**Comment by Rory80Hz** [comment]
Hey there! I'm a colleague of bleach's, i'd be interested in having a chat about what work you are doing with AWS service brokers, could you put me in touch with the right person?

**Comment by frodenas** [comment]
@Rory80Hz Can you please send me an email at frodenas at pivotal.io so?

**Comment by markdcunha** [comment]
Pivotal Cloud Foundry has developed a Service Broker for AWS available on Pivotal Network. https://network.pivotal.io/products/pcf-service-broker-for-aws

**Comment by mogul** [comment]
@frodenas given the lack of intent to maintain this repository, would you mind moving it to the Cloud Foundry Community org so others can take it up?

**Comment by frodenas** [comment]
@mogul I'm no longer a Pivotal employee, you should ask them.

**Comment by joshuamckenty** [comment]
I’m happy to move it.

**Comment by mogul** [comment]
Excellent, thanks @joshuamckenty!
